<?php


// Define the constants

define('APP_ROOT',      DOCUMENT_ROOT . 'app' . DIRECTORY_SEPARATOR);
define('PUBLIC_DIR', DOCUMENT_ROOT . 'public' . DIRECTORY_SEPARATOR);
define('LOGS_DIR', APP_ROOT . 'logs' . DIRECTORY_SEPARATOR);


define('SRC_FOLDER',    DOCUMENT_ROOT . 'src' . DIRECTORY_SEPARATOR);
define('BOOTSTRAP_FOLDER', DOCUMENT_ROOT . 'bootstrap' . DIRECTORY_SEPARATOR);
define('PUBLIC_VIEWS_FOLDER', PUBLIC_DIR . 'views' . DIRECTORY_SEPARATOR);
define('COMPONENTS_FOLDER', PUBLIC_VIEWS_FOLDER . 'components' . DIRECTORY_SEPARATOR);


define('CONTROLLERS_DIR',SRC_FOLDER . 'Controllers' . DIRECTORY_SEPARATOR);
define('MODELS_DIR', SRC_FOLDER . 'Models' . DIRECTORY_SEPARATOR);
define('VIEWS_DIR', SRC_FOLDER . 'Views' . DIRECTORY_SEPARATOR);
define('CORE_DIR', SRC_FOLDER . 'Core' . DIRECTORY_SEPARATOR);
define('ENTITIES_DIR', SRC_FOLDER . 'Entities' . DIRECTORY_SEPARATOR);
define('UTILS_DIR', SRC_FOLDER . 'Utils' . DIRECTORY_SEPARATOR);